apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
      - name: app
        image: metadata:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
        ports:
        - containerPort: 8081